// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gallery_go/app"
	"gallery_go/controller"
	"gallery_go/repository"
	"gallery_go/service"
	"github.com/go-playground/validator"
	"github.com/google/wire"
	"net/http"
)

// Injectors from injector.go:

func initializedServer() *http.Server {
	userRepository := repository.NewUserRepository()
	db := app.NewDB()
	validate := validator.New()
	userService := service.NewUserService(userRepository, db, validate)
	userController := controller.NewUserController(userService)
	router := app.NewRouter(userController)
	server := NewServer(router)
	return server
}

// injector.go:

var userSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController)
